"📷 RENDERER":
  - changed-files: "rawrbox.render/**/*"

"🧮 MATH":
  - changed-files: "rawrbox.math/**/*"

"🖼️ UI":
  - changed-files: "rawrbox.ui/**/*"

"⚒️ UTILS":
  - changed-files: "rawrbox.utils/**/*"

"🐲 SAMPLES":
  - changed-files: "samples/**/*"

"🧱 3D PHYSICS":
  - changed-files: "rawrbox.physics_3d/**/*"

"🏀 2D PHYSICS":
  - changed-files: "rawrbox.physics_2d/**/*"

"🎺 BASS":
  - changed-files: "rawrbox.bass/**/*"

"💼 RESOURCES":
  - changed-files: "rawrbox.resources/**/*"

"💽 ENGINE":
  - changed-files: "rawrbox.engine/**/*"

"🧪 TESTS":
  - changed-files: "**/tests/**/*.cpp"

"🎞 WEBM":
  - changed-files: "rawrbox.webm/**/*"

"🧙‍♂️ ASSIMP":
  - changed-files: "rawrbox.assimp/**/*"

"📜 SCRIPTING":
  - changed-files:
      [
        "rawrbox.scripting/**/*",
        "rawrbox.bass/**/scripting/*",
        "rawrbox.network/**/scripting/*",
        "rawrbox.render/**/scripting/*",
        "rawrbox.resources/**/scripting/*",
        "rawrbox.ui/**/scripting/*",
        "**/*.lua",
        "**/*.luau",
      ]

"FEATURE":
  - head-branch: "^features/"

"BUG":
  - head-branch: "^bugfixes/"

"IMPROVEMENTS":
  - head-branch: "^improvements/"
