'📷 RENDERER':
    - 'render/**/*'

'🧮 MATH':
    - 'math/**/*'

'🖼️ UI':
    - 'ui/**/*'

'⚒️ UTILS':
    - 'utils/**/*'

'🐲 SAMPLES':
    - 'samples/**/*'

'🪛 DEBUG':
    - 'debug/**/*'

'🧱 PHYSICS':
    - 'physics/**/*'

'🎺 BASS':
    - 'bass/**/*'

'💼 RESOURCES':
    - 'resources/**/*'

'💽 ENGINE':
    - 'engine/**/*'

'🧪 TESTS':
    - '**/tests/**/*.cpp'
