"📷 RENDERER":
  - changed-files:
      - any-glob-to-any-file: "rawrbox.render/**/*"

"🧮 MATH":
  - changed-files:
      - any-glob-to-any-file: "rawrbox.math/**/*"

"🖼️ UI":
  - changed-files:
  - any-glob-to-any-file: "rawrbox.ui/**/*"

"⚒️ UTILS":
  - changed-files:
      - any-glob-to-any-file: "rawrbox.utils/**/*"

"🐲 SAMPLES":
  - changed-files:
      - any-glob-to-any-file: "samples/**/*"

"🧱 3D PHYSICS":
  - changed-files:
      - any-glob-to-any-file: "rawrbox.physics_3d/**/*"

"🏀 2D PHYSICS":
  - changed-files:
      - any-glob-to-any-file: "rawrbox.physics_2d/**/*"

"🎺 BASS":
  - changed-files:
      - any-glob-to-any-file: "rawrbox.bass/**/*"

"💼 RESOURCES":
  - changed-files:
      - any-glob-to-any-file: "rawrbox.resources/**/*"

"💽 ENGINE":
  - changed-files:
      - any-glob-to-any-file: "rawrbox.engine/**/*"

"🧪 TESTS":
  - changed-files:
      - any-glob-to-any-file: "**/tests/**/*.cpp"

"🎞 WEBM":
  - changed-files:
      - any-glob-to-any-file: "rawrbox.webm/**/*"

"🧙‍♂️ ASSIMP":
  - changed-files:
      - any-glob-to-any-file: "rawrbox.assimp/**/*"

"📜 SCRIPTING":
  - changed-files:
      - any-glob-to-any-file:
          [
            "rawrbox.scripting/**/*",
            "rawrbox.bass/**/scripting/*",
            "rawrbox.network/**/scripting/*",
            "rawrbox.render/**/scripting/*",
            "rawrbox.resources/**/scripting/*",
            "rawrbox.ui/**/scripting/*",
            "**/*.lua",
            "**/*.luau",
          ]

"FEATURE":
  - head-branch: ["^features/"]

"BUG":
  - head-branch: ["^bugfixes/"]

"IMPROVEMENTS":
  - head-branch: ["^improvements/"]
