"📷 RENDERER":
  - changed-files: "render/**/*"

"🧮 MATH":
  - changed-files: "math/**/*"

"🖼️ UI":
  - changed-files: "ui/**/*"

"⚒️ UTILS":
  - changed-files: "utils/**/*"

"🐲 SAMPLES":
  - changed-files: "samples/**/*"

"🧱 PHYSICS":
  - changed-files: "physics/**/*"

"🎺 BASS":
  - changed-files: "bass/**/*"

"💼 RESOURCES":
  - changed-files: "resources/**/*"

"💽 ENGINE":
  - changed-files: "engine/**/*"

"🧪 TESTS":
  - changed-files: "**/tests/**/*.cpp"

"FEATURE":
  - head-branch: "^features/"

"BUG":
  - head-branch: "^bugfixes/"

"IMPROVEMENTS":
  - head-branch: "^improvements/"
