name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
exclude-labels:
  - "dependencies"
  - "github_actions"
  - "🧪 TESTS"
  - "TODO"
  - "⚠️ SKIP_LINTER ⚠️"
  - "⚠️ SKIP_TESTS ⚠️"
  - "⚠️ UPLOAD ⚠️"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "FEATURE"
  minor:
    labels:
      - "IMPROVEMENTS"
      - "🧙‍♂️ ASSIMP"
      - "🎺 BASS"
      - "💽 ENGINE"
      - "🧮 MATH"
      - "🛰 NETWORK"
      - "📷 RENDERER"
      - "💼 RESOURCES"
      - "📜 SCRIPTING"
      - "🖼️ UI"
      - "⚒️ UTILS"
      - "🎞 WEBM"
      - "🏀 2D PHYSICS"
      - "🧱 3D PHYSICS"
      - "💨 STEAMWORKS"
  patch:
    labels:
      - "BUG"
  default: patch
template: |
  ## What’s Changed

  $CHANGES
