name: CI/CD - COMMENTS
on:
    pull_request:
        types: [labeled, unlabeled]

jobs:
    comment:
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - name: Find comment
              uses: peter-evans/find-comment@v2
              id: fc
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  comment-author: 'github-actions[bot]'
                  body-includes: ## NOTICE  - A LUA API change was detected ⚠

            - name: Create / Update comment
              uses: peter-evans/create-or-update-comment@v3
              if: contains(github.event.pull_request.labels.*.name, '📜 SCRIPTING')
              with:
                  comment-id: ${{ steps.fc.outputs.comment-id }}
                  issue-number: ${{ github.event.pull_request.number }}
                  body: |
                      ## NOTICE  - A LUA API change was detected ⚠
                      - Ensure [**wiki** / **ias-lib**](https://github.com/edunad/rawrbox-wiki) is up to date.
                  edit-mode: replace
